version: '3.5'

# To Join any other app setup using another network, change name and set external = true
networks:
  default:
    name: elastic
    external: false

# will contain all elasticsearch data.
volumes:
  elasticsearch-data:

secrets:
  elasticsearch.keystore:
    file: ./solomon-secrets/${ENV}/ssl/keystore/elasticsearch.keystore
  elastic.ca:
    file: ./solomon-secrets/${ENV}/ssl/certs/ca/ca.crt
  elasticsearch.certificate:
    file: ./solomon-secrets/${ENV}/ssl/certs/elasticsearch/elasticsearch.crt
  elasticsearch.key:
    file: ./solomon-secrets/${ENV}/ssl/certs/elasticsearch/elasticsearch.key
  elasticsearch.http.keystore:
    file: ./solomon-secrets/${ENV}/http/elasticsearch/http.p12
  kibana.certificate:
    file: ./solomon-secrets/${ENV}/ssl/certs/kibana/kibana.crt
  kibana.key:
    file: ./solomon-secrets/${ENV}/ssl/certs/kibana/kibana.key
  kibana.http.ca:
    file: ./solomon-secrets/${ENV}/http/kibana/elasticsearch-ca.pem

services:
  es0:
    image: ksd/es:${ELK_VERSION}
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}
    restart: unless-stopped
    environment:
      ELASTICSEARCH_SCHEME: ${ELASTICSEARCH_SCHEME}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTIC_CLUSTER_NAME: ${ELASTIC_CLUSTER_NAME}
      ELASTIC_NODE_NAME: ${ELASTIC_NODE_NAME}
      ELASTIC_INIT_MASTER_NODE: ${ELASTIC_INIT_MASTER_NODE}
      ELASTIC_DISCOVERY_SEEDS: ${ELASTIC_DISCOVERY_SEEDS}
      ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP} -Des.enforce.bootstrap.checks=true
      bootstrap.memory_lock: "true"
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
      - ./elasticsearch/config/elasticsearch-master.yml:/usr/share/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/log4j2.properties:/usr/share/elasticsearch/config/log4j2.properties
    secrets:
      - source: elasticsearch.keystore
        target: /usr/share/elasticsearch/config/elasticsearch.keystore
      - source: elastic.ca
        target: /usr/share/elasticsearch/config/certs/ca.crt
      - source: elasticsearch.certificate
        target: /usr/share/elasticsearch/config/certs/elasticsearch.crt
      - source: elasticsearch.key
        target: /usr/share/elasticsearch/config/certs/elasticsearch.key
      - source: elasticsearch.http.keystore
        target: /usr/share/elasticsearch/config/certs/http.p12
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 200000
        hard: 200000

  kibana:
    image: ksd/kibana:${ELK_VERSION}
    build:
      context: kibana/
      args:
        ELK_VERSION: $ELK_VERSION
    restart: unless-stopped
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    environment:
      ELASTICSEARCH_SCHEME: ${ELASTICSEARCH_SCHEME}
      KIBANA_SCHEME: ${KIBANA_SCHEME}
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ELASTICSEARCH_HOST_PORT: ${ELASTICSEARCH_HOST}:${ELASTICSEARCH_PORT}
    secrets:
      - source: elastic.ca
        target: /certs/ca.crt
      - source: kibana.certificate
        target: /certs/kibana.crt
      - source: kibana.key
        target: /certs/kibana.key
      - source: kibana.http.ca
        target: /certs/elasticsearch-ca.pem
    ports:
      - "5601:5601"
    links: 
      - "es0:elasticsearch"
    depends_on: 
      - es0
